### ISSUE TITLE
Unable to change the order of operations/functions on the UML class diagram

### ISSUE THREAD

**Issue by Techrone** [ModelioOpenSource/Modelio#56] opened 2023-03-31 12:00 UTC
Hi,

I am currently struggling to change the order of the operations for a specific class in the class diagram. This diagram was created from scratch with no java source code imported to build the UML diagram.

I have went through the documentation that was provided with the application, but find nothing to address this current problem. I am currently running Modelio 5.1.

Is there a way for me to change the order of the operations without needing to delete and recreate every operation for this specific class?

**Comment by aabherve** [comment] 2023-03-31 14:12
Hi,

You can change the order of operations in diagram with the following steps :

1. Manually hide operations in the diagrams (selects all operations and Right Click -> Hide Selection)
2. Go to the model explorer side and order the operations of the class.
3. Unhide operations in the diagram by Drag and Drop from the model explorer

**Comment by mvdw** [comment] 2023-04-18 13:45
In Modelio 4.1, you could select the attribute in the model explorer, and press Ctrl-U for moving it up, and CTRL-D for moving it down.

**Comment by mvdw** [comment] 2023-04-26 12:04
Why was this closed? Is the problem solved?
The problem is that 1. there is no description of this in the documentation and 2. the feature is invisible.

**Comment by IrinaNeculita** [comment] 2023-04-26 15:33
Hello,
Was closed by mistake. 

We have a comment above about this : 

You can change the order of operations in diagram with the following steps :

    Manually hide operations in the diagrams (selects all operations and Right Click -> Hide Selection)
    Go to the model explorer side and order the operations of the class.
    Unhide operations in the diagram by Drag and Drop from the model explorer.

You can unmask all or just some of the attributes/operations.

On the online help we have - Modelio Modeler - Modelio Diagrams -  Showing and masking elements in diagrams 

Showing all the internal elements of a class

The "Symbol" view on an element allows you to define an automatic unmask policy for its internal elements, according to their visibility:

    All: Show all elements

    All public: Show only public elements

    All non-private: Mask private elements

    Manual: Show or mask elements individually


https://www.modeliosoft.com/modeliosaas-help/531/en/index.jsp?topic=%2Forg.modelio.documentation.modeliomodeler%2Fhtml%2FIndex_saas.html&cp=13 
![modelio_Gzojny2GnM](https://user-images.githubusercontent.com/130666068/234626584-683653e2-c32f-4025-97d7-06cb88d07f24.gif)

**Comment by mvdw** [comment] 2023-04-26 15:54
Sorry, this part of my remark above was wrong: " 2. the feature is invisible" - since in the explorer the yellow arrows indicate the feature.

**Closed** 2023-05-05 13:58 UTC
